### PR TITLE
Serialize template contents

### PR DESCRIPTION
**Pull request by fabianbieler**
Template tags require special treatment for their contents to be processed.

A unit test is included for demonstration purposes.

PS: Thanks to the brave team for maintaining this project.
If you could consider this PR I would be so happy!

### CODE REVIEW

**Review by rillian — APPROVED** [review]
Looks reasonable. Thanks for the contribution!

**Comment by rillian** [comment]
@fabianbieler do you want to sign your commit, or shall I land it under mine?

**Comment by fabianbieler** [comment]
Sorry for not reading the contribution requirements properly and thanks for the reminder.
The commit is signed now.

**Review by rillian — APPROVED** [review]
Thanks for updating!

**Pull request merged**
